[project]
name = "scanhub-patient-manager"
version = "0.0.1"
description = "ScanHub patient manager"
authors = [
    {name = "David Schote", email = "david.schote@brain-link.de"},
]
readme = "README.md"
license = { text = "GPL-3.0-only with custom exception" }
requires-python = ">=3.13,<3.14"
dependencies = [
    "uvicorn[standard]>=0.17.5",
    "asyncpg>=0.30.0",
    "psycopg2-binary>=2.9.6",
    "async-sqlalchemy>=1.0.0",
    "scanhub-libraries",
]

[dependency-groups]
test = ["coverage", "codecov", "pytest"]
docs = ["sphinx", "sphinx_rtd_theme"]
lint = ["ruff>=0.16.3", "mypy>=2.3.1"]

[tool.uv]
package = false

[tool.uv.sources]
scanhub-libraries = { workspace = true }

[tool.ruff]
extend = "../../pyproject.toml"
src = ["app"]
target-version = "py310"
