version: "3"
services:

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - patient-manager
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  patient-manager:
    container_name: sh-patient-manager
    image: sh-patient-manager
    restart: unless-stopped
    build: ./patient-manager
    command: bash -c "uvicorn app.main:app --port 8000 --host 0.0.0.0 --reload"
    depends_on:
    - patients_db
    volumes:
    - ./patient-manager:/app/
    ports:
      - 8000:8000

  patients_db:
    container_name: sh-db-patients
    image: postgres:12.13-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: data
      POSTGRES_USER: brainlink
      POSTGRES_DB: patients-data
    ports:
      - "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8060:8060
  #   # Change default adminer port
  #   command:
  #     - 'php'
  #     - '-S'
  #     - '[::]:8060'
  #     - '-t'
  #     - '/var/www/html'

