version: "3"
services:

  orthanc:
    image: jodogne/orthanc-plugins
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=scanhub_dicom_server
    volumes:
      - ./orthanc-db:/var/lib/orthanc/db/

  frontend:
    container_name: ScanHubFrontend
    image: scanhub_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  backend:
    image: scanhub_backend
    restart: unless-stopped
    container_name: ScanHubUIBackend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn scanhub.api:app --port 8000 --host 0.0.0.0 --reload"
    depends_on:
    - postgres
    volumes:
    - ./backend:/scanhub
    ports:
      - 8000:8000

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    container_name: Storage
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  workflowspython:
    restart: always
    container_name: WorkflowsPython
    build: 
      context: ./workflows-python
      dockerfile: ./Dockerfile
    environment:
      "AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;QueueEndpoint=http://storage:10001/devstoreaccount1;TableEndpoint=http://storage:10002/devstoreaccount1;"
    volumes:
    - ./workflows-python:/home/site/wwwroot
    ports:
      - 81:80
    depends_on:
      - storage

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: Database
    environment:
      POSTGRES_PASSWORD: brainLinkIstCool2022UndLecker
      POSTGRES_USER: brainLink
      POSTGRES_DB: scanhub
      
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: PostgreSQLAdmin
    ports:
      - 8080:8080

volumes:
  db_data:
  
secrets:
  orthanc.json:
    file: orthanc.json
