version: "3"
services:

  frontend:
    container_name: ScanHubFrontend
    image: scanhub_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  backend:
    image: scanhub_backend
    restart: unless-stopped
    container_name: ScanHubUIBackend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn scanhub.api:app --port 8000 --host 0.0.0.0 --reload"
    depends_on:
    - postgres
    volumes:
    - ./backend:/scanhub
    ports:
      - 8000:8000

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: Database
    environment:
      POSTGRES_PASSWORD: patient_data
      POSTGRES_USER: brainlink
      POSTGRES_DB: scanhub
      
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: PostgreSQLAdmin
    ports:
      - 8080:8080
