x-airflow-common:
  &airflow-common
  build: ./services/airflow
  image: ${AIRFLOW_IMAGE_NAME:-extending_airflow:latest}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    AIRFLOW__CLI__ENDPOINT_URL: http://localhost:8081
  volumes:
    - ./services/airflow/dags:/opt/airflow/dags
    - ./services/airflow/logs:/opt/airflow/logs
    - ./services/airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    airflow-database:
      condition: service_healthy

services:

  # SERVICES
  # Workflow manager, device manager and exam manager create data tables in postgres DB
  workflow-manager:
    container_name: workflow-manager
    build: 
      context: ./services/workflow-manager
      args: 
        - BASE_IMG=${SCANHUB_BASE_IMAGE}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/workflow-manager/app/:/app/
      - data_lake:/app/data_lake/
    ports:
      - 8001:8000
    environment:
      - DB_URI=postgresql://brainlink:9ArU5*Sr@scanhub-database/sh_db
      - DB_URI_ASYNC=postgresql+asyncpg://brainlink:9ArU5*Sr@scanhub-database/sh_db
    healthcheck:
      # TODO: host.docker.internal is only working with docker desktop, must be replaced in product
      test: ["CMD", "curl", "http://workflow-manager:8000/api/v1/workflow/health/readiness"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      scanhub-database:
        condition: service_healthy

  device-manager:
    container_name: device-manager
    build:
      context: ./services/device-manager
      args: 
        - BASE_IMG=${SCANHUB_BASE_IMAGE}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/device-manager/app/:/app/
      - data_lake:/app/data_lake/
    ports:
      - 8002:8000
    environment:
      - DB_URI=postgresql://brainlink:9ArU5*Sr@scanhub-database/sh_db
      - DB_URI_ASYNC=postgresql+asyncpg://brainlink:9ArU5*Sr@scanhub-database/sh_db
    healthcheck:
      # TODO: host.docker.internal is only working with docker desktop, must be replaced in product
      test: ["CMD", "curl", "http://device-manager:8000/api/v1/device/health/readiness"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      scanhub-database:
        condition: service_healthy

  exam-manager:
    container_name: exam-manager
    build: 
      context: ./services/exam-manager
      args: 
        - BASE_IMG=${SCANHUB_BASE_IMAGE}
        # - BASE_IMG=scanhub-base
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/exam-manager/app/:/app/
      - data_lake:/app/data_lake/
    ports:
      - 8004:8000
    environment:
      - DB_URI=postgresql://brainlink:9ArU5*Sr@scanhub-database/sh_db
      - DB_URI_ASYNC=postgresql+asyncpg://brainlink:9ArU5*Sr@scanhub-database/sh_db
    healthcheck:
      # TODO: host.docker.internal is only working with docker desktop, must be replaced in product
      test: ["CMD", "curl", "http://exam-manager:8000/api/v1/exam/health/readiness"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      scanhub-database:
        condition: service_healthy
      device-manager:
        condition: service_healthy
      workflow-manager:
        condition: service_healthy

  patient-manager:
    container_name: patient-manager
    build: 
      context: ./services/patient-manager
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8100
    volumes:
    - ./services/patient-manager/app:/app/
    ports:
      - 8100:8100
    environment:
      - DB_URI=postgresql://brainlink:data@patient-database/patients-data
      - DB_URI_ASYNC=postgresql+asyncpg://brainlink:data@patient-database/patients-data
    depends_on:
      patient-database:
        condition: service_healthy

  user-login-manager:
    container_name: user-login-manager
    build: 
      context: ./services/user-login-manager
      args: 
        - BASE_IMG=${SCANHUB_BASE_IMAGE}
        # - BASE_IMG=scanhub-base
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/user-login-manager/app/:/app/
      - data_lake:/app/data_lake/
    ports:
      - 8005:8000
    environment:
      - DB_URI=postgresql://brainlink:9ArU5*Sr@scanhub-database/sh_db
      - DB_URI_ASYNC=postgresql+asyncpg://brainlink:9ArU5*Sr@scanhub-database/sh_db
    healthcheck:
      # TODO: host.docker.internal is only working with docker desktop, must be replaced in product
      test: ["CMD", "curl", "http://user-login-manager:8000/api/v1/userlogin/health/readiness"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      scanhub-database:
        condition: service_healthy


  # MRI Sequence Service
  sequence-manager:
    container_name: sequence-manager
    build: 
      context: ./services/mri/sequence-manager
      args: 
        - BASE_IMG=${SCANHUB_BASE_IMAGE}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/mri/sequence-manager/app/:/app/
      - data_lake:/app/data_lake/
    ports:
      - 8003:8000
    environment:
      - MONGODB_USER=root
      - MONGODB_PASSWORD=example
      - MONGODB_HOST=sequence-database
      - MONGODB_PORT=27017
      - MONGODB_DB=mri_sequences_db
      - MONGODB_COLLECTION_NAME=mri_sequences
    depends_on:
      sequence-database:
        condition: service_healthy


  # MRI Reconstruction Services
  cartesian-reco-service:
    container_name: service-cartesian-reco
    build:
      context: ./services/mri/recos/cartesian-reco-service
      args: 
        - BASE_IMG=${SCANHUB_BASE_IMAGE}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/mri/recos/cartesian-reco-service/app/:/app/
      - data_lake:/app/data_lake/

  
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

  # DATABASES
  # Airflow Postgres Database:
  airflow-database:
    container_name: airflow-db
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  # Scanhub Postgres Database: Contains exams, procedures, records, jobs, devices and workflows 
  scanhub-database:
    container_name: db-scanhub
    image: postgres:15.2-bullseye
    restart: always # unless-stopped
    volumes:
      - postgres_data_scanhub:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: brainlink
      POSTGRES_PASSWORD: 9ArU5*Sr
      POSTGRES_DB: sh_db
    healthcheck:  
      # Workflow, device and exam microservices depend on healthy postgres database
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s 
    ports:
      - "5433:5432"

  # Patient database
  patient-database:
    container_name: patient-db
    image: postgres:15.2-bullseye
    restart: always
    volumes:
      - postgres_data_patient:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: brainlink
      POSTGRES_DB: patients-data
      POSTGRES_PASSWORD: data
    ports:
      - "5432:5432"
    healthcheck:  
      # init-db container is started, after health check passed
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s 


  # MRI Sequence mongo database: Contains (pulseq) mri sequence files
  sequence-database:
    container_name: db-sequence
    image: mongo
    restart: always # unless-stopped
    volumes:
      - mongodb_data_sequence:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 9ArU5*Sr
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh sequence-database:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "27017:27017"


  # API Gateway
  nginx:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./infrastructure/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      device-manager:
        condition: service_healthy
      workflow-manager:
        condition: service_healthy
      exam-manager: 
        condition: service_healthy
      sequence-manager:
        condition: service_started


  # FRONTEND/SCANHUB-UI    # development-launcher.sh expects this container description in line 308-321
  scanhub-ui:
    container_name: scanhub-ui
    build:
      context: ./scanhub-ui
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: "development" # use "development" or "production"
    depends_on:
      - patient-manager
    volumes:
      - ./scanhub-ui/src:/app/src
    ports:
      - 3000:3000


volumes:
  data_lake:
  mongodb_data_sequence:
  postgres_data_scanhub:
  postgres_data_patient:
  airflow-db-volume: