version: "3"
services:

  frontend:
    container_name: Frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  backend:
    container_name: Backend
    image: backend
    restart: unless-stopped
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn scanhub.api:app --port 8000 --host 0.0.0.0 --reload"
    depends_on:
    - postgres
    volumes:
    - ./backend:/scanhub
    ports:
      - 8000:8000

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: Patient-Database
    environment:
      POSTGRES_PASSWORD: patient_data
      POSTGRES_USER: brainlink
      POSTGRES_DB: scanhub

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: DB-Admin
    ports:
      - 8060:8060
    # Change default adminer port
    command:
      - 'php'
      - '-S'
      - '[::]:8060'
      - '-t'
      - '/var/www/html'
    # entrypoint:
    #   - 'entrypoint.sh'
    #   - 'docker-php-entrypoint'

  # Postgres Admin Tool
  # fepgadmin:
  #   container_name: fepg-admin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: info@brain-link.de
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8071:8071"