version: "3"
services:
  # ui:
  #   image: scanhub_ui
  #   restart: unless-stopped
  #   container_name: ScanHubUI
  #   build: 
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   volumes:
  #   - ./frontend:/scanhub
  #   ports:
  #     - 3000:3000

  uiserver:
    image: scanhub_ui_server
    restart: unless-stopped
    container_name: ScanHubUIServer
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    env_file: ./server/.env_file
    command: bash -c "uvicorn scanhub.api:app --port 8000 --host 0.0.0.0 --reload"
    depends_on:
    - postgres
    volumes:
    - ./server:/scanhub
    ports:
      - 8000:8000

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    container_name: Storage
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  workflowspython:
    restart: always
    container_name: WorkflowsPython
    build: 
      context: ./workflows-python
      dockerfile: ./Dockerfile
    environment:
      "AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;QueueEndpoint=http://storage:10001/devstoreaccount1;TableEndpoint=http://storage:10002/devstoreaccount1;"
    volumes:
    - ./workflows-python:/home/site/wwwroot
    ports:
      - 81:80
    depends_on:
      - storage

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: Database
    environment:
      POSTGRES_PASSWORD: brainLinkIstCool2022UndLecker
      POSTGRES_USER: brainLink
      POSTGRES_DB: scanhub
      
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: PostgreSQLAdmin
    ports:
      - 8080:8080

volumes:
  db_data:
