version: "3.9"
services:
  app:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./server/.env_file
    image: scanhub_new
    command: bash -c "uvicorn scanhub.main:app --port 8000 --host 0.0.0.0 --reload"
    depends_on:
    - postgres
    volumes:
    - .:/scanhub
    ports:
    - 8000:8000

# https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite
# https://docs.microsoft.com/en-us/samples/azure-samples/automated-testing-with-azurite/automated-testing-with-azure/
# https://azure.microsoft.com/en-us/features/storage-explorer/#overview
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"

#https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob
  # azureblobstorage:
  #     image: mcr.microsoft.com/azure-blob-storage:latest

  azurefunctions:
    image: mcr.microsoft.com/azure-functions/python

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: brainLinkIstCool2022UndLecker
      POSTGRES_USER: brainLink
      POSTGRES_DB: scanhub
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db_data:
