export { deferred } from './deferred'
export { sleep } from './sleep'
export { serializeForm } from './serializeForm'
export { range } from './range'
export { trimSlashes } from './trimSlashes'
export { clamp } from './clamp'
