[project]
name = "scanhub-device-sdk"
version = "0.0.1"
description = "Software development kit to connect devices to ScanHub."
authors = [
    {name = "David Schote", email = "david.schote@brain-link.de"},
    {name = "Johannes Behrens", email = "johannes.behrens@brain-link.de"}
]
readme = "README.md"
license = { text = "GPL-3.0-only with custom exception" }
license-files = ["LICENSE", "LICENSE.GPL3", "LICENSE.GPL3-EXCEPT"]
requires-python = ">=3.13,<3.14"
dependencies = [
    "numpy>=2.3.2",
    "websockets>=15.0.1",
    "scanhub-libraries",
]

[tool.uv.sources]
scanhub-libraries = { path = "../../services/base/shared_libs", editable = true }

[dependency-groups]
lint = ["ruff>=0.16.3", "mypy>=2.3.1"]
example = ["zenodo-get>=3.0.3"]

[tool.ruff]
extend = "../../pyproject.toml"
src = ["src"]
target-version = "py313"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sdk"]
