[project]
name = "scanhub-libraries"
version = "0.0.2"
license = { text = "GPL-3.0-only with custom exception" }
license-files = ["LICENSE", "LICENSE.GPL3", "LICENSE.GPL3-EXCEPT"]
requires-python = ">=3.13,<3.14"
dependencies = [
    "pydantic>=2.11.7,<3.0.0",
    "sqlalchemy>=2.0.43,<3.0.0",
    "dagster>=1.11.6,<2.0.0",
    "fastapi>=0.116.1,<0.117.0",
    "passlib[argon2]>=1.7.4,<2.0.0",
    "pydantic-settings>=2.10.1,<3.0.0",
]

[project.urls]
Homepage = "https://github.com/brain-link/scanhub"

[dependency-groups]
lint = ["ruff>=0.16.3", "mypy>=2.3.1"]

[tool.ruff]
src = ["src"]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
# Enable linters
# E = pycodestyle (error)
# W = pycodestyle (warning)
# F = Pyflakes
# S = flake8-bandit
# I = isort
# N = pep8-naming
# D = pydocstyle
select = ["E", "W", "F", "S", "I", "N", "D"]

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
files = ["src"]
python_version = "3.13"
warn_return_any = false
check_untyped_defs = true
warn_no_return = true
warn_unreachable = true
ignore_missing_imports = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/scanhub_libraries"]
