/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface DatetimeUpdated
 */
export interface DatetimeUpdated {
}
/**
 * Device registration request pydantic model.  (to be sent by user first adding the device to the platform).
 * @export
 * @interface DeviceCreationRequest
 */
export interface DeviceCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof DeviceCreationRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreationRequest
     */
    'description': string;
    /**
     * 
     * @type {DeviceCreationRequestStatus}
     * @memberof DeviceCreationRequest
     */
    'status'?: DeviceCreationRequestStatus;
}
/**
 * 
 * @export
 * @interface DeviceCreationRequestStatus
 */
export interface DeviceCreationRequestStatus {
}
/**
 * 
 * @export
 * @interface DeviceId
 */
export interface DeviceId {
}
/**
 * 
 * @export
 * @interface DeviceName
 */
export interface DeviceName {
}
/**
 * Device pydantic output model.
 * @export
 * @interface DeviceOut
 */
export interface DeviceOut {
    /**
     * 
     * @type {DeviceName}
     * @memberof DeviceOut
     */
    'device_name'?: DeviceName;
    /**
     * 
     * @type {SerialNumber}
     * @memberof DeviceOut
     */
    'serial_number'?: SerialNumber;
    /**
     * 
     * @type {Manufacturer}
     * @memberof DeviceOut
     */
    'manufacturer'?: Manufacturer;
    /**
     * 
     * @type {Modality}
     * @memberof DeviceOut
     */
    'modality'?: Modality;
    /**
     * 
     * @type {DeviceCreationRequestStatus}
     * @memberof DeviceOut
     */
    'status'?: DeviceCreationRequestStatus;
    /**
     * 
     * @type {Site}
     * @memberof DeviceOut
     */
    'site'?: Site;
    /**
     * 
     * @type {Parameter}
     * @memberof DeviceOut
     */
    'parameter'?: Parameter;
    /**
     * 
     * @type {string}
     * @memberof DeviceOut
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceOut
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceOut
     */
    'datetime_created': string;
    /**
     * 
     * @type {DatetimeUpdated}
     * @memberof DeviceOut
     */
    'datetime_updated'?: DatetimeUpdated;
}
/**
 * Pydantic definition of a commands.
 * @export
 * @enum {string}
 */

export const DeviceStatus = {
    Online: 'ONLINE',
    Offline: 'OFFLINE',
    Busy: 'BUSY',
    Error: 'ERROR'
} as const;

export type DeviceStatus = typeof DeviceStatus[keyof typeof DeviceStatus];


/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface Manufacturer
 */
export interface Manufacturer {
}
/**
 * 
 * @export
 * @interface Modality
 */
export interface Modality {
}
/**
 * 
 * @export
 * @interface Parameter
 */
export interface Parameter {
}
/**
 * 
 * @export
 * @interface SerialNumber
 */
export interface SerialNumber {
}
/**
 * 
 * @export
 * @interface Site
 */
export interface Site {
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'input'?: any;
    /**
     * 
     * @type {object}
     * @memberof ValidationError
     */
    'ctx'?: object;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DevicesApi - axios parameter creator
 * @export
 */
export const DevicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create device database entry.  Only devices which are created by a user via this endpoint and have the device_id and device_token that result from this call configured correctly can later connect and register.  Parameters ---------- request:     DeviceCreationRequest to create device in Scanhub.     Further details of the device are later provided by the device itself.  Return ------ device_token:     the token of the device which the user should copy manually to the configuration file of the device.  device_id:     the id of the device, should be copied to the devices config file together with the device_token.
         * @summary Create Device
         * @param {DeviceCreationRequest} deviceCreationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDevice: async (deviceCreationRequest: DeviceCreationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceCreationRequest' is not null or undefined
            assertParamExists('createDevice', 'deviceCreationRequest', deviceCreationRequest)
            const localVarPath = `/api/v1/device/createdevice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceCreationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response indicating the success or failure of the deletion.
         * @summary Delete Device
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDevice: async (deviceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('deleteDevice', 'deviceId', deviceId)
            const localVarPath = `/api/v1/device/{device_id}`
                .replace(`{${"device_id"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a specific device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response containing the information about the device
         * @summary Get Device
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevice: async (deviceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('getDevice', 'deviceId', deviceId)
            const localVarPath = `/api/v1/device/{device_id}`
                .replace(`{${"device_id"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve the list of registered devices.  Returns -------     List[Device]: The list of registered devices.
         * @summary Get Devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/device/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Trigger an MRI acquisition for the given task.  Fetches the task from the protocol manager, looks up the assigned sequence and device, sends the scan-start command via the device\'s open WebSocket, and marks the task as STARTED.
         * @summary Trigger Acquisition
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerAcquisition: async (taskId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('triggerAcquisition', 'taskId', taskId)
            const localVarPath = `/api/v1/device/trigger_acquisition/{task_id}`
                .replace(`{${"task_id"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update acquisition/device parameter.  Parameters ---------- device_id     Id of the device to be updated payload     Parameter dictionary  Returns -------     Parameter dictionary  Raises ------ HTTPException     404: Not found
         * @summary Update acquisition/device parameter
         * @param {DeviceId} deviceId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDeviceParameter: async (deviceId: DeviceId, requestBody: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('updateDeviceParameter', 'deviceId', deviceId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('updateDeviceParameter', 'requestBody', requestBody)
            const localVarPath = `/api/v1/device/parameter/{device_id}`
                .replace(`{${"device_id"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DevicesApi - functional programming interface
 * @export
 */
export const DevicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DevicesApiAxiosParamCreator(configuration)
    return {
        /**
         * Create device database entry.  Only devices which are created by a user via this endpoint and have the device_id and device_token that result from this call configured correctly can later connect and register.  Parameters ---------- request:     DeviceCreationRequest to create device in Scanhub.     Further details of the device are later provided by the device itself.  Return ------ device_token:     the token of the device which the user should copy manually to the configuration file of the device.  device_id:     the id of the device, should be copied to the devices config file together with the device_token.
         * @summary Create Device
         * @param {DeviceCreationRequest} deviceCreationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDevice(deviceCreationRequest: DeviceCreationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDevice(deviceCreationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.createDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response indicating the success or failure of the deletion.
         * @summary Delete Device
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDevice(deviceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDevice(deviceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.deleteDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a specific device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response containing the information about the device
         * @summary Get Device
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevice(deviceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDevice(deviceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.getDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve the list of registered devices.  Returns -------     List[Device]: The list of registered devices.
         * @summary Get Devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DeviceOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDevices(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.getDevices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Trigger an MRI acquisition for the given task.  Fetches the task from the protocol manager, looks up the assigned sequence and device, sends the scan-start command via the device\'s open WebSocket, and marks the task as STARTED.
         * @summary Trigger Acquisition
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerAcquisition(taskId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerAcquisition(taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.triggerAcquisition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update acquisition/device parameter.  Parameters ---------- device_id     Id of the device to be updated payload     Parameter dictionary  Returns -------     Parameter dictionary  Raises ------ HTTPException     404: Not found
         * @summary Update acquisition/device parameter
         * @param {DeviceId} deviceId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDeviceParameter(deviceId: DeviceId, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDeviceParameter(deviceId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.updateDeviceParameter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DevicesApi - factory interface
 * @export
 */
export const DevicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DevicesApiFp(configuration)
    return {
        /**
         * Create device database entry.  Only devices which are created by a user via this endpoint and have the device_id and device_token that result from this call configured correctly can later connect and register.  Parameters ---------- request:     DeviceCreationRequest to create device in Scanhub.     Further details of the device are later provided by the device itself.  Return ------ device_token:     the token of the device which the user should copy manually to the configuration file of the device.  device_id:     the id of the device, should be copied to the devices config file together with the device_token.
         * @summary Create Device
         * @param {DeviceCreationRequest} deviceCreationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDevice(deviceCreationRequest: DeviceCreationRequest, options?: any): AxiosPromise<any> {
            return localVarFp.createDevice(deviceCreationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response indicating the success or failure of the deletion.
         * @summary Delete Device
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDevice(deviceId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteDevice(deviceId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a specific device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response containing the information about the device
         * @summary Get Device
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevice(deviceId: string, options?: any): AxiosPromise<DeviceOut> {
            return localVarFp.getDevice(deviceId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve the list of registered devices.  Returns -------     List[Device]: The list of registered devices.
         * @summary Get Devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevices(options?: any): AxiosPromise<Array<DeviceOut>> {
            return localVarFp.getDevices(options).then((request) => request(axios, basePath));
        },
        /**
         * Trigger an MRI acquisition for the given task.  Fetches the task from the protocol manager, looks up the assigned sequence and device, sends the scan-start command via the device\'s open WebSocket, and marks the task as STARTED.
         * @summary Trigger Acquisition
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerAcquisition(taskId: string, options?: any): AxiosPromise<any> {
            return localVarFp.triggerAcquisition(taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update acquisition/device parameter.  Parameters ---------- device_id     Id of the device to be updated payload     Parameter dictionary  Returns -------     Parameter dictionary  Raises ------ HTTPException     404: Not found
         * @summary Update acquisition/device parameter
         * @param {DeviceId} deviceId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDeviceParameter(deviceId: DeviceId, requestBody: { [key: string]: any; }, options?: any): AxiosPromise<DeviceOut> {
            return localVarFp.updateDeviceParameter(deviceId, requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DevicesApi - object-oriented interface
 * @export
 * @class DevicesApi
 * @extends {BaseAPI}
 */
export class DevicesApi extends BaseAPI {
    /**
     * Create device database entry.  Only devices which are created by a user via this endpoint and have the device_id and device_token that result from this call configured correctly can later connect and register.  Parameters ---------- request:     DeviceCreationRequest to create device in Scanhub.     Further details of the device are later provided by the device itself.  Return ------ device_token:     the token of the device which the user should copy manually to the configuration file of the device.  device_id:     the id of the device, should be copied to the devices config file together with the device_token.
     * @summary Create Device
     * @param {DeviceCreationRequest} deviceCreationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public createDevice(deviceCreationRequest: DeviceCreationRequest, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).createDevice(deviceCreationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response indicating the success or failure of the deletion.
     * @summary Delete Device
     * @param {string} deviceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public deleteDevice(deviceId: string, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).deleteDevice(deviceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a specific device.  Args -------     device_id (str): The ID of the device.  Returns -------     dict: The response containing the information about the device
     * @summary Get Device
     * @param {string} deviceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public getDevice(deviceId: string, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).getDevice(deviceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve the list of registered devices.  Returns -------     List[Device]: The list of registered devices.
     * @summary Get Devices
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public getDevices(options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).getDevices(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Trigger an MRI acquisition for the given task.  Fetches the task from the protocol manager, looks up the assigned sequence and device, sends the scan-start command via the device\'s open WebSocket, and marks the task as STARTED.
     * @summary Trigger Acquisition
     * @param {string} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public triggerAcquisition(taskId: string, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).triggerAcquisition(taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update acquisition/device parameter.  Parameters ---------- device_id     Id of the device to be updated payload     Parameter dictionary  Returns -------     Parameter dictionary  Raises ------ HTTPException     404: Not found
     * @summary Update acquisition/device parameter
     * @param {DeviceId} deviceId 
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public updateDeviceParameter(deviceId: DeviceId, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).updateDeviceParameter(deviceId, requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Readiness health endpoint.  Inspects SQLAlchemy engine and checks if the device table exists.
         * @summary Readiness
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthReadiness: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/device/health/readiness`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Readiness health endpoint.  Inspects SQLAlchemy engine and checks if the device table exists.
         * @summary Readiness
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthReadiness(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthReadiness(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthReadiness']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Readiness health endpoint.  Inspects SQLAlchemy engine and checks if the device table exists.
         * @summary Readiness
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthReadiness(options?: any): AxiosPromise<any> {
            return localVarFp.healthReadiness(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Readiness health endpoint.  Inspects SQLAlchemy engine and checks if the device table exists.
     * @summary Readiness
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthReadiness(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthReadiness(options).then((request) => request(this.axios, this.basePath));
    }
}



