# .yarnrc.yml
yarnPath: .yarn/releases/yarn-4.9.2.cjs
nodeLinker: node-modules

# Make some vtk peer deps optional (VTK pulls them in but you don't need them in the browser)
packageExtensions:
  "@kitware/vtk.js@*":
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true
      "autoprefixer":
        optional: true
      "wslink":
        optional: true

  # (Optional) silence noisy peers in common tooling stacks
  inquirer@8.*:
    peerDependencies:
      "@types/node": "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true

  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true