nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

packageExtensions:
  "@kitware/vtk.js@*":
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true
      "autoprefixer":
        optional: true
      "wslink":
        optional: true
