[project]
name = "scanhub-user-manager"
version = "0.0.1"
description = "Provides functionality for user login and user management."
authors = [
    {name = "David Schote", email = "david.schote@brain-link.de"},
    {name = "Christoph Dinh", email = "christoph.dinh@brain-link.de"},
    {name = "Ben Wilhelm", email = "ben.wilhelm@uniklinik-freiburg.de"}
]
readme = "README.md"
license = { text = "GPL-3.0-only with custom exception" }
requires-python = ">=3.13,<3.14"
dependencies = [
    "asyncpg>=0.30.0",
    "uvicorn>=0.22.0",
    "psycopg2-binary>=2.9.6",
    "python-multipart>=0.0.6",
    "async-sqlalchemy>=1.0.0",
    "typing-extensions>=4.14.1",
    "scanhub-libraries",
]

[dependency-groups]
test = ["coverage", "codecov", "pytest"]
docs = ["sphinx", "sphinx_rtd_theme"]
lint = ["ruff>=0.16.3", "mypy>=2.3.1"]

[tool.uv]
package = false

[tool.uv.sources]
scanhub-libraries = { workspace = true }

[tool.ruff]
extend = "../../pyproject.toml"
src = ["app"]
target-version = "py310"
