name: 'Build'

on:
  push:
    branches:
      - '*'
  pull_request:


jobs:
  compose:
    name: 'docker-compose'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: |
          docker build -t scanhub-base ./services/base && 
          docker compose build --build-arg BASE_IMG=scanhub-base:latest &&
          docker compose up -d
