name: 'build'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: 'docker-compose'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build scanhub-ui
        run: docker-compose up -d
