name: 'Build'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_image:
    name: 'build_base_image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the base image
        run: docker build -t scanhub-base ./base
  compose:
    name: 'docker-compose'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
