name: 'Build'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Containerize:
    name: 'LintiContainerize Applications'

    runs-on: ubuntu-latest
    env:
      working-directory: ./applications

    strategy:
      matrix:
        python-version: ['3.11']
        applications: [
          "mri/cartesian_reco_app",
        ]

    continue-on-error: True

    steps:

      - uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - run: pip install holoscan monai-deploy-app-sdk
