name: 'Build'

on:
  workflow_run:
    workflows: ["Deploy to GHCR"]
    types: 
      - completed
  # push:
  #   branches:
  #     - '*'
  # pull_request:
  #   branches:
  #     - '*'

jobs:
  compose:
    name: 'docker-compose'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: |
          docker build -t scanhub-base ./services/base && 
          docker-compose up -d
