name: Deploy to GHCR
on:
  workflow_dispatch:
  push:
    branches: ['main', 'ghcr_base_image']
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/scanhub-base
  SERVICE_PATH: services/base

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              ${{ env.SERVICE_PATH }}
              
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # # set latest tag for main branch
            # type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # set latest tag always for now
            type=raw,value=latest,enable=true
            # dynamically set the sha as a custom tagif it is main
            type=raw,value={{sha}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # dynamically set the sha as a custom tag prefixed with dev if it's not main
            type=raw,value=dev-{{sha}},enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SERVICE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
