name: 'linter'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  job:
    name: 'Lint Patient-Manager'
    runs-on: ubuntu-latest

    env:
      working-directory: ./patient-manager

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Project
        run: poetry install --no-interaction --with lint
