name: 'linter'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  pylint:
    name: 'Lint Patient-Manager'
    runs-on: ubuntu-latest

    env:
      working-directory: ./patient-manager

    strategy:
      matrix:
        python-version: ["3.10"]
        
    continue-on-error: True
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true

      - name: Install Project
        working-directory: ${{env.working-directory}}
        run: poetry install --no-interaction --with lint
        
      - name: Run pylint
        working-directory: ${{env.working-directory}}
        run: |
          pylint
          continue-on-error: true
          
      - name: Run flake8
        working-directory: ${{env.working-directory}}
        run: |
          flake8
          continue-on-error: true
        
      - name: Run mypy
        working-directory: ${{env.working-directory}}
        run: |
          mypy
          continue-on-error: true
          
      - name: Run pydocstyle
        working-directory: ${{env.working-directory}}
        run: |
          pydocstyle
          continue-on-error: true
      

          
