name: 'static-tests-frontend'

on:
  pull_request:

jobs:
  linting-frontend:
    name: 'Linting frontend'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./scanhub-ui

    continue-on-error: true   # lowercase true is YAML boolean

    steps:
      - uses: actions/checkout@v4

      # Cache Yarn's global cache directory for faster installs
      - name: Get Yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Enable Corepack (for Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run linter
        run: yarn lint
