name: static-tests-frontend

on:
  pull_request:
    branches: [ main ]

jobs:
  linting-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scanhub-ui
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version

      - name: Get Yarn cache dir
        id: yarn-cache
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
